// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

package inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Identifier struct {
	GUID                 string   `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

type Item struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Subset               float64  `protobuf:"fixed64,3,opt,name=Subset,proto3" json:"Subset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Item) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Item) GetSubset() float64 {
	if m != nil {
		return m.Subset
	}
	return 0
}

type Incomplete struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Incomplete) Reset()         { *m = Incomplete{} }
func (m *Incomplete) String() string { return proto.CompactTextString(m) }
func (*Incomplete) ProtoMessage()    {}
func (*Incomplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2}
}

func (m *Incomplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Incomplete.Unmarshal(m, b)
}
func (m *Incomplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Incomplete.Marshal(b, m, deterministic)
}
func (m *Incomplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Incomplete.Merge(m, src)
}
func (m *Incomplete) XXX_Size() int {
	return xxx_messageInfo_Incomplete.Size(m)
}
func (m *Incomplete) XXX_DiscardUnknown() {
	xxx_messageInfo_Incomplete.DiscardUnknown(m)
}

var xxx_messageInfo_Incomplete proto.InternalMessageInfo

func (m *Incomplete) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Complete struct {
	Identifier           *Identifier `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	Incomplete           *Incomplete `protobuf:"bytes,2,opt,name=Incomplete,proto3" json:"Incomplete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Complete) Reset()         { *m = Complete{} }
func (m *Complete) String() string { return proto.CompactTextString(m) }
func (*Complete) ProtoMessage()    {}
func (*Complete) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{3}
}

func (m *Complete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Complete.Unmarshal(m, b)
}
func (m *Complete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Complete.Marshal(b, m, deterministic)
}
func (m *Complete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Complete.Merge(m, src)
}
func (m *Complete) XXX_Size() int {
	return xxx_messageInfo_Complete.Size(m)
}
func (m *Complete) XXX_DiscardUnknown() {
	xxx_messageInfo_Complete.DiscardUnknown(m)
}

var xxx_messageInfo_Complete proto.InternalMessageInfo

func (m *Complete) GetIdentifier() *Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *Complete) GetIncomplete() *Incomplete {
	if m != nil {
		return m.Incomplete
	}
	return nil
}

type AddItemRequest struct {
	Identifier           *Identifier `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	Item                 *Item       `protobuf:"bytes,2,opt,name=Item,proto3" json:"Item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddItemRequest) Reset()         { *m = AddItemRequest{} }
func (m *AddItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddItemRequest) ProtoMessage()    {}
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{4}
}

func (m *AddItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemRequest.Unmarshal(m, b)
}
func (m *AddItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemRequest.Marshal(b, m, deterministic)
}
func (m *AddItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemRequest.Merge(m, src)
}
func (m *AddItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddItemRequest.Size(m)
}
func (m *AddItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemRequest proto.InternalMessageInfo

func (m *AddItemRequest) GetIdentifier() *Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *AddItemRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type RemoveItemRequest struct {
	Identifier           *Identifier `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	Item                 *Item       `protobuf:"bytes,2,opt,name=Item,proto3" json:"Item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RemoveItemRequest) Reset()         { *m = RemoveItemRequest{} }
func (m *RemoveItemRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveItemRequest) ProtoMessage()    {}
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{5}
}

func (m *RemoveItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveItemRequest.Unmarshal(m, b)
}
func (m *RemoveItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveItemRequest.Marshal(b, m, deterministic)
}
func (m *RemoveItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveItemRequest.Merge(m, src)
}
func (m *RemoveItemRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveItemRequest.Size(m)
}
func (m *RemoveItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveItemRequest proto.InternalMessageInfo

func (m *RemoveItemRequest) GetIdentifier() *Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *RemoveItemRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Identifier)(nil), "inventory.Identifier")
	proto.RegisterType((*Item)(nil), "inventory.Item")
	proto.RegisterType((*Incomplete)(nil), "inventory.Incomplete")
	proto.RegisterType((*Complete)(nil), "inventory.Complete")
	proto.RegisterType((*AddItemRequest)(nil), "inventory.AddItemRequest")
	proto.RegisterType((*RemoveItemRequest)(nil), "inventory.RemoveItemRequest")
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor_cde9ec64f0d2c859) }

var fileDescriptor_cde9ec64f0d2c859 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0x85, 0xaf, 0x7c, 0x0c, 0x11, 0xe3, 0x18, 0x49, 0x45, 0x0f, 0xcd, 0x1a, 0x93, 0x9e,
	0x4a, 0x02, 0xc1, 0xc4, 0x8b, 0x09, 0xa1, 0x4a, 0x7a, 0xf0, 0xb2, 0xc6, 0x1f, 0x00, 0x32, 0x10,
	0x12, 0xda, 0xc5, 0xb2, 0x25, 0xf2, 0xcb, 0xfc, 0x7b, 0xa6, 0xdb, 0x52, 0x57, 0x01, 0x0f, 0x1e,
	0xbc, 0x75, 0xe7, 0xcd, 0x9b, 0x79, 0xf3, 0xfa, 0xe0, 0x28, 0x1c, 0x45, 0xa3, 0x19, 0xc5, 0xde,
	0x32, 0x16, 0x52, 0x60, 0x6d, 0x1e, 0xad, 0x29, 0x92, 0x22, 0xde, 0xb4, 0x2e, 0x66, 0x42, 0xcc,
	0x16, 0xd4, 0x56, 0xc0, 0x38, 0x99, 0xb6, 0x29, 0x5c, 0xca, 0x4d, 0xd6, 0xc7, 0x1c, 0x80, 0x60,
	0x42, 0x91, 0x9c, 0x4f, 0xe7, 0x14, 0x23, 0x42, 0x65, 0xf8, 0x1c, 0xf8, 0xb6, 0xe1, 0x18, 0x6e,
	0x8d, 0xab, 0x6f, 0xf6, 0x00, 0x95, 0x40, 0x52, 0x88, 0x0d, 0x30, 0x0b, 0xc4, 0x0c, 0x7c, 0x6c,
	0x82, 0xd5, 0x0f, 0x45, 0x12, 0x49, 0xdb, 0x74, 0x0c, 0xb7, 0xc2, 0xf3, 0x57, 0x5a, 0x7f, 0x4a,
	0xc6, 0x2b, 0x92, 0x76, 0xd9, 0x31, 0x5c, 0x83, 0xe7, 0x2f, 0xd6, 0x05, 0x08, 0xa2, 0x17, 0x11,
	0x2e, 0x17, 0x24, 0x09, 0xaf, 0xe1, 0x5f, 0x3a, 0x75, 0x65, 0x1b, 0x4e, 0xd9, 0xad, 0x77, 0x8e,
	0xbd, 0x42, 0xaf, 0x97, 0xd6, 0x79, 0x86, 0xb2, 0x37, 0xf8, 0x3f, 0xd8, 0x52, 0x7a, 0xba, 0x54,
	0x25, 0xa4, 0xde, 0x39, 0xd3, 0x79, 0x05, 0xc8, 0xf5, 0x9b, 0x7a, 0xfa, 0x5e, 0xa5, 0xf5, 0x1b,
	0xad, 0x00, 0xb9, 0xd6, 0xc8, 0x16, 0xd0, 0xe8, 0x4f, 0x26, 0x4a, 0x0b, 0xbd, 0x26, 0xb4, 0x92,
	0xbf, 0xdd, 0x7f, 0x95, 0xf9, 0x97, 0x6f, 0xde, 0x39, 0x54, 0x81, 0x4c, 0xc0, 0x09, 0xa7, 0x50,
	0xac, 0xe9, 0x8f, 0x16, 0x76, 0xde, 0x4d, 0xa8, 0x3e, 0x66, 0x89, 0xc1, 0x2e, 0x94, 0x87, 0x24,
	0x71, 0xff, 0xe8, 0xd6, 0xa9, 0x56, 0xde, 0xfe, 0x0b, 0x56, 0xc2, 0x1b, 0xb0, 0x06, 0x31, 0x8d,
	0x24, 0xe1, 0x7e, 0x33, 0x0f, 0xf1, 0xee, 0xa0, 0x9a, 0xfb, 0x8a, 0xe7, 0x5a, 0xc7, 0x57, 0xaf,
	0x5b, 0x4d, 0x2f, 0x0b, 0xad, 0xb7, 0x0d, 0xad, 0x77, 0x9f, 0x86, 0x96, 0x95, 0xd0, 0x07, 0xf8,
	0x74, 0x0a, 0x2f, 0xb5, 0x11, 0x3b, 0x06, 0xfe, 0x30, 0xe5, 0x16, 0x2c, 0x9f, 0x54, 0xaa, 0x0e,
	0x5c, 0x7d, 0x90, 0x3a, 0xb6, 0x54, 0xa5, 0xfb, 0x11, 0x00, 0x00, 0xff, 0xff, 0x49, 0x2c, 0x55,
	0x61, 0x71, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
	Get(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Complete, error)
	Create(ctx context.Context, in *Incomplete, opts ...grpc.CallOption) (*Complete, error)
	AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveItem(ctx context.Context, in *RemoveItemRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*empty.Empty, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) Get(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Complete, error) {
	out := new(Complete)
	err := c.cc.Invoke(ctx, "/inventory.Manager/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Create(ctx context.Context, in *Incomplete, opts ...grpc.CallOption) (*Complete, error) {
	out := new(Complete)
	err := c.cc.Invoke(ctx, "/inventory.Manager/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/inventory.Manager/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) RemoveItem(ctx context.Context, in *RemoveItemRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/inventory.Manager/RemoveItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Delete(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/inventory.Manager/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
	Get(context.Context, *Identifier) (*Complete, error)
	Create(context.Context, *Incomplete) (*Complete, error)
	AddItem(context.Context, *AddItemRequest) (*empty.Empty, error)
	RemoveItem(context.Context, *RemoveItemRequest) (*empty.Empty, error)
	Delete(context.Context, *Identifier) (*empty.Empty, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.Manager/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Get(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Incomplete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.Manager/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Create(ctx, req.(*Incomplete))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.Manager/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).AddItem(ctx, req.(*AddItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_RemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).RemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.Manager/RemoveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).RemoveItem(ctx, req.(*RemoveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.Manager/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Delete(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Manager_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Manager_Create_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _Manager_AddItem_Handler,
		},
		{
			MethodName: "RemoveItem",
			Handler:    _Manager_RemoveItem_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Manager_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager.proto",
}
